### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by Zombitch** [OpenZWave/node-openzwave-shared#103]
Hi,

I'm not able to install the whole package on my raspberry pi although I followed instruction here : 

https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-raspbian.md

When I launch the command "npm install openzwave-shared" I got this error :

```
pi@raspberrypi:~/Projects/test$ npm install openzwave-shared

> openzwave-shared@1.2.0 preinstall /home/pi/Projects/jarvis/node_modules/.staging/openzwave-shared-7466178b
> node lib/install-ozw.js


> openzwave-shared@1.2.0 install /home/pi/Projects/jarvis/node_modules/openzwave-shared
> node-gyp rebuild

Package libopenzwave was not found in the pkg-config search path.
Perhaps you should add the directory containing `libopenzwave.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libopenzwave' found
gyp: Call to 'PKG_CONFIG_PATH=/usr/local/lib/pkgconfig pkg-config --variable=libdir libopenzwave' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.11+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Projects/yoyo/node_modules/openzwave-shared
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 4.4.11+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "openzwave-shared"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openzwave-shared
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Projects/toto/npm-debug.log
pi@raspberrypi:~/Projects/toto$ npm install openzwave-sh 
```
And indeed, I did not find any file name "libopenzwave.pc" on the computer.

Any idea on how to resolve this problem ?

Thanks :)

**Comment by ekarak** [comment]
Building OpenZWave on Raspberry can be a pain. Please try to download the pre-built debian packages from https://github.com/ekarak/openzwave-debs-raspbian/tree/master/v1.4.79 and then install them (`sudo dpkg -i *openzwave*.deb`)

**Comment by cczus** [comment]
FYI, when I download the .deb files and run the package, it says they are not valid deb files.  Verifying them gives me the same result.

**Comment by tuckwat** [comment]
@cczus try this:  

`wget https://github.com/ekarak/openzwave-debs-raspbian/raw/master/v1.4.79/libopenzwave1.3_1.4.79.gfaea7dd_armhf.deb

wget https://github.com/ekarak/openzwave-debs-raspbian/raw/master/v1.4.79/libopenzwave1.3-dev_1.4.79.gfaea7dd_armhf.deb

sudo dpkg -i libopenzwave*.deb`

They are valid deb packages but if you copy the link from the address bar it will fail.  I usually right click on the download button and choose "copy link".
