### ISSUE TITLE
Fresh Install Test Not Run

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/node-openzwave-shared#111]
After following instructions to install on Raspberry, running `test2.js` I receive:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'openzwave-shared'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/Documents/Sentinel/test2.js:1:75)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

I installed globally openzwave-shared
`npm install openzwave-shared -g`

And the top of test2.js is 
`var ZWave = require('openzwave-shared');`

**Comment by ekarak** [comment]
Resolving - you shouldn't use `npm install -g`, unless you also set the NODE_PATH env var.
