### ISSUE TITLE
Registry returned 404 for GET on http://registry.npmjs.org/node-red-openzwave-shared

### ISSUE THREAD

**Issue by Stephan35** [OpenZWave/node-openzwave-shared#148]
Hello,
I cannot install it,
```
xxx:~/.node-red$ npm install node-red-openzwave-shared
npm ERR! Linux 3.4.113-sun8i
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-openzwave-shared"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/node-red-openzwave-shared
npm ERR! 404 
npm ERR! 404  'node-red-openzwave-shared' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/.node-red/npm-debug.log

```

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-red-openzwave-shared' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData node-red-openzwave-shared
8 silly fetchNamedPackageData node-red-openzwave-shared
9 silly mapToRegistry name node-red-openzwave-shared
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'node-red-openzwave-shared',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'node-red-openzwave-shared',
12 silly mapToRegistry   name: 'node-red-openzwave-shared',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/node-red-openzwave-shared
14 verbose request uri http://registry.npmjs.org/node-red-openzwave-shared
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:31:31 PM
17 verbose request id 666dd4d083daeed3
18 http request GET http://registry.npmjs.org/node-red-openzwave-shared
19 http 404 http://registry.npmjs.org/node-red-openzwave-shared
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sat, 04 Mar 2017 17:31:32 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lhr6325-LHR',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1488648692.044685,VS0,VE379',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sat, 04 Mar 2017 17:31:32 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lhr6325-LHR',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1488648692.044685,VS0,VE379',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on http://registry.npmjs.org/node-red-openzwave-shared
22 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:969:12)
22 silly fetchPackageMetaData  error for node-red-openzwave-shared { Error: Registry returned 404 for GET on http://registry.npmjs.org/node-red-openzwave-shared
22 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:969:12)
22 silly fetchPackageMetaData   pkgid: 'node-red-openzwave-shared',
22 silly fetchPackageMetaData   statusCode: 404,
22 silly fetchPackageMetaData   code: 'E404' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on http://registry.npmjs.org/node-red-openzwave-shared
27 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
27 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
27 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:187:22)
27 verbose stack     at emitTwo (events.js:106:13)
27 verbose stack     at Request.emit (events.js:191:7)
27 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1048:10)
27 verbose stack     at emitOne (events.js:96:13)
27 verbose stack     at Request.emit (events.js:188:7)
27 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:969:12)
28 verbose statusCode 404
29 verbose pkgid node-red-openzwave-shared
30 verbose cwd /home/xxx/.node-red
31 error Linux 3.4.113-sun8i
32 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-openzwave-shared"
33 error node v6.10.0
34 error npm  v3.10.10
35 error code E404
36 error 404 Registry returned 404 for GET on http://registry.npmjs.org/node-red-openzwave-shared
37 error 404
38 error 404 'node-red-openzwave-shared' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]

```

Here is what i tried : 
```code
npm config set registry https://registry.npmjs.org/
npm config set registry http://registry.npmjs.org/
npm update
```

thanks for support
Best regards

**Comment by ekarak** [comment]
1st of all this is the repo for the openzwave libary, not the Node-Red adapter (which is built on top of it). 
2nd the npm package is 'node-red-contrib-openzwave'

Thanks

**Comment by Stephan35** [comment]
Sorry for my error .
Best regards
