### ISSUE TITLE
npm install -g openzwave-shared not works on Linux Ubuntu 17.04 - node.js 7.9.0

### ISSUE THREAD

**Issue by francescozambon4** [OpenZWave/node-openzwave-shared#158]
Hi,
command "npm install -g openzwave-shared" fails using Ubuntu 17.04 and Node.js 7.9.0:
francesco@ubuntu:~$ npm install -g openzwave-shared

```
> openzwave-shared@1.3.3 preinstall /home/francesco/opt/node-v7.9.0-linux-x64/lib/node_modules/.staging/openzwave-shared-503378ce
> node lib/install-ozw.js


> openzwave-shared@1.3.3 install /home/francesco/opt/node-v7.9.0-linux-x64/lib/node_modules/openzwave-shared
> node-gyp rebuild

find: ‘undefined’: No such file or directory
gyp: Call to 'find undefined -name ZWSecurity.h | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/francesco/opt/node-v7.9.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-36-generic
gyp ERR! command "/home/francesco/opt/node-v7.9.0-linux-x64/bin/node" "/home/francesco/opt/node-v7.9.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/francesco/opt/node-v7.9.0-linux-x64/lib/node_modules/openzwave-shared
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/home/francesco/opt/node-v7.9.0-linux-x64/bin/node" "/home/francesco/opt/node-v7.9.0-linux-x64/bin/npm" "install" "-g" "openzwave-shared"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! openzwave-shared@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openzwave-shared
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/francesco/.npm/_logs/2017-04-12T14_15_50_823Z-debug.log
```

**Comment by ekarak** [comment]
this is weird, as I explicitly check for arguments passed onto find. Will try to replicate.

**Comment by ekarak** [comment]
cant replicate on docker. Found another issue though:
```
/bin/sh: 1: node: not found
gyp: Call to 'node -p "require('./lib/ozwpaths.js').libdir"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

**Comment by ekarak** [comment]
please retry with version 1.3.4 which I've just released.
