### ISSUE TITLE
Add value to "TypeError: setValue: OpenZWave valueId not found"

### ISSUE THREAD

**Issue by NicSil** [OpenZWave/node-openzwave-shared#165]
A lot of issues about the "TypeError: setValue: OpenZWave valueId not found" here, all closed.
But I still have it. I suppose its not a bug, but a real bad input value.
Would it be possible to help the debug by giving at least which valueId is not found?

**Comment by ekarak** [comment]
ok, here's a branch that raises some meaningful errors. Given this test code:

```js
var ZWaveModule = require('openzwave-shared');
var zwave = new ZWaveModule();

console.log(zwave);

try{ zwave.pressButton();             } catch (e) {	console.log(e); }
try{ zwave.pressButton({foo: 'bar'}); } catch (e) {	console.log(e); }
try{ zwave.pressButton({node_id: 2}); } catch (e) {	console.log(e); }
try{ zwave.pressButton({node_id: 2, class_id: 37, instance:1, index: 1}); } catch (e) {	console.log(e); }
```

you'll be getting back these errors:

```TypeError: OpenZWave valueId not found. Pass either a JS object with {node_id, class_id, instance, index} or the raw values in this order.
    at Object.<anonymous> (/home/ekarak/src/gh/OpenZWave/node-openzwave-shared/test3.js:6:12)
...
TypeError: OpenZWave valueId object not found: {"foo":"bar"}
    at Object.<anonymous> (/home/ekarak/src/gh/OpenZWave/node-openzwave-shared/test3.js:7:12)
...
TypeError: OpenZWave valueId object not found: {"node_id":2}
    at Object.<anonymous> (/home/ekarak/src/gh/OpenZWave/node-openzwave-shared/test3.js:8:12)
...
TypeError: OpenZWave valueId not found: 2-37-1-1
    at Object.<anonymous> (/home/ekarak/src/gh/OpenZWave/node-openzwave-shared/test3.js:9:12)
```

**Comment by ekarak** [comment]
https://github.com/OpenZWave/node-openzwave-shared/tree/feature/revealBadValueId

**Comment by ekarak** [comment]
resolving - feature merged into master

**Comment by NicSil** [comment]
cool.
