### ISSUE TITLE
Cannot install on Raspberry Pi

### ISSUE THREAD

**Issue by Stubbs** [OpenZWave/node-openzwave-shared#20]
Trying to install the openzwave node-red module & I get the following error:

```
pi@rpib ~/.node-red $ npm install node-red-contrib-openzwave
/
> typechecker@2.0.8 preinstall /home/pi/.node-red/node_modules/node-red-contrib-openzwave/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> openzwave-shared@1.0.8 install /home/pi/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared
> node-gyp rebuild

make: Entering directory '/home/pi/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared/build'
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
In file included from ../src/openzwave.cc:18:0:
../src/openzwave.hpp:30:21: fatal error: Manager.h: No such file or directory
compilation terminated.
openzwave_shared.target.mk:102: recipe for target 'Release/obj.target/openzwave_shared/src/openzwave.o' failed
make: *** [Release/obj.target/openzwave_shared/src/openzwave.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.18.7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! openzwave-shared@1.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.0.8 install script.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-red-contrib-openzwave"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by ekarak** [comment]
The problem is that you're missing OpenZWave headers from your path:
`../src/openzwave.hpp:30:21: fatal error: Manager.h: No such file or directory`
Please install OpenZWave development package or simply download and compile OZW by its sources.
