### ISSUE TITLE
Error on Windows Build 'openzwave/Manager.h':No such file or directory 

### ISSUE THREAD

**Issue by sogaani** [OpenZWave/node-openzwave-shared#218]
An error will occur when building the library with windows.

``` shell
git clone https://github.com/sogaani/node-openzwave-shared.git
cd node-openzwave-shared
npm install

///

C:\Users\16737\Documents\git\test\myopenzwave\node-openzwave-shared>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
このソリューション内のプロジェクトを 1 度に 1 つずつビルドします。並行ビルドを有効にするには、"/m" スイッチを追加してください。
  callbacks.cc
  openzwave.cc
  openzwave-config.cc
  openzwave-driver.cc
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-config.cc) [C:\Users\16737\Documents\git\te
st\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\callbacks.cc) [C:\Users\16737\Documents\git\test\myop
enzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave.cc) [C:\Users\16737\Documents\git\test\myop
enzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
  openzwave-groups.cc
  openzwave-management.cc
  openzwave-network.cc
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-driver.cc) [C:\Users\16737\Documents\git\te
st\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
  openzwave-nodes.cc
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-management.cc) [C:\Users\16737\Documents\gi
t\test\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-groups.cc) [C:\Users\16737\Documents\git\te
st\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
  openzwave-polling.cc
  openzwave-scenes.cc
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-network.cc) [C:\Users\16737\Documents\git\t
est\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
  openzwave-values.cc
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-nodes.cc) [C:\Users\16737\Documents\git\tes
t\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
  utils.cc
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-scenes.cc) [C:\Users\16737\Documents\git\te
st\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-polling.cc) [C:\Users\16737\Documents\git\t
est\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
  win_delay_load_hook.cc
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\openzwave-values.cc) [C:\Users\16737\Documents\git\te
st\myopenzwave\node-openzwave-shared\build\openzwave_shared.vcxproj]
c:\users\16737\documents\git\test\myopenzwave\node-openzwave-shared\src\openzwave.hpp(29): fatal error C1083: include ファイルを開けません。
'openzwave/Manager.h':No such file or directory (ソース ファイルをコンパイルしています ..\src\utils.cc) [C:\Users\16737\Documents\git\test\myopenzw
ave\node-openzwave-shared\build\openzwave_shared.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\16737\Documents\git\test\myopenzwave\node-openzwave-shared
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\16737\AppData\Roaming\npm-cache\_logs\2018-02-21T05_05_40_049Z-debug.log
```

**Comment by ekarak** [comment]
Version 1.4.3 just released. This includes the fix in #222 and adds Appveyor CI support for Windows builds.
