### ISSUE TITLE
Help installing on ubuntu 15.04 (x64)

### ISSUE THREAD

**Issue by g00dnatur3** [OpenZWave/node-openzwave-shared#22]
Hi,

Thank you very much for creating this library!

Im trying to get it working, here is what I have done so far:

step 1) 

I installed Openzwave --> make && make install
I found the "libopenzwave.so.1.3"  in the "/usr/local/lib64"
I added "/usr/local/lib64" to the PATH environment variable.

Step 2)

I ran the following:

sudo npm install -g openzwave-shared

Step 3)

My app.js has only 1 line of code 

var OZW = require('openzwave-shared');

I get the following error:

initialising OpenZWave addon (/home/developer/workspace/zwavedemo/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node)
module.js:355
  Module._extensions[extension](this, filename);
                               ^

Error: libopenzwave.so.1.3: cannot open shared object file: No such file or directory
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/developer/workspace/zwavedemo/node_modules/openzwave-shared/lib/openzwave-shared.js:27:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by jfishbein** [comment]
You might need to update your shared library cache. Try running `sudo ldconfig` and then try running your app again.

**Comment by g00dnatur3** [comment]
Ok i fixed this bug by doing this:

export LD_LIBRARY_PATH=/usr/local/lib64

However, now I have a version mismatch bug:

initialising OpenZWave addon (/home/developer/workspace/zwavedemo/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node)
module.js:355
  Module._extensions[extension](this, filename);
                               ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/developer/workspace/zwavedemo/node_modules/openzwave-shared/lib/openzwave-shared.js:27:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by g00dnatur3** [comment]
I got it working!!!

Thanks :)

**Comment by benburkhart1** [comment]
sudo ldconfig /usr/local/lib64

would have worked and probably been better.

**Comment by japita-se** [comment]
@g00 how did you accomplish?
