### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Lineaire** [OpenZWave/node-openzwave-shared#356]
Hello, I'm having trouble installing the library. I install deb open-zwave but the problem persists ...

```
root@DebianVm:/home/sofian/Documents# npm install openzwave-shared
> openzwave-shared@1.5.9 preinstall /home/sofian/Documents/node_modules/openzwave-shared
> node lib/install-ozw.js


> openzwave-shared@1.5.9 install /home/sofian/Documents/node_modules/openzwave-shared
> node-gyp rebuild

make : on entre dans le répertoire « /home/sofian/Documents/node_modules/openzwave-shared/build »
  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
In file included from ../src/openzwave.hpp:28,
                 from ../src/callbacks.cc:18:
/home/sofian/Documents/node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
/home/sofian/Documents/node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘                                                                    void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../src/openzwave.hpp:27,
                 from ../src/callbacks.cc:18:
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/13.0.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node:                                                                    :ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallback                                                                    Info<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
/home/sofian/Documents/node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::                                                                    ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackIn                                                                    fo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
In file included from ../src/openzwave.hpp:28,
                 from ../src/openzwave.cc:18:
/home/sofian/Documents/node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
/home/sofian/Documents/node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘                                                                    void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from /home/sofian/Documents/node_modules/nan/nan.h:54,
                 from ../src/openzwave.hpp:28,
                 from ../src/openzwave.cc:18:
../src/openzwave.cc: At global scope:
/root/.cache/node-gyp/13.0.1/include/node/node.h:571:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Obj                                                                    ect>, v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-f                                                                    unction-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.cache/node-gyp/13.0.1/include/node/node.h:605:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/openzwave.cc:330:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(openzwave_shared, OZW::init)
 ^~~~~~~~~~~
In file included from ../src/openzwave.hpp:27,
                 from ../src/openzwave.cc:18:
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/13.0.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node:                                                                    :ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallback                                                                    Info<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
/home/sofian/Documents/node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::                                                                    ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackIn                                                                    fo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-config.o
In file included from ../src/openzwave.hpp:28,
                 from ../src/openzwave-config.cc:18:
/home/sofian/Documents/node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
/home/sofian/Documents/node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘                                                                    void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../src/openzwave.hpp:27,
                 from ../src/openzwave-config.cc:18:
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/13.0.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node:                                                                    :ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallback                                                                    Info<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
/home/sofian/Documents/node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::                                                                    ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackIn                                                                    fo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-driver.o
In file included from ../src/openzwave.hpp:28,
                 from ../src/openzwave-driver.cc:18:
/home/sofian/Documents/node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
/home/sofian/Documents/node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘                                                                    void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../src/openzwave.hpp:27,
                 from ../src/openzwave-driver.cc:18:
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/13.0.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node:                                                                    :ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallback                                                                    Info<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
/home/sofian/Documents/node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::                                                                    ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackIn                                                                    fo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-groups.o
In file included from ../src/openzwave.hpp:28,
                 from ../src/openzwave-groups.cc:18:
/home/sofian/Documents/node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
/home/sofian/Documents/node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘                                                                    void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/openzwave-groups.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE OZW::OZW::GetAssociationsInstances(Nan::NAN_METHO                                                                    D_ARGS_TYPE)’:
../src/openzwave-groups.cc:98:4: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v                                                                    8::Integer>::return_t)’
    );
    ^
In file included from ../src/openzwave.hpp:27,
                 from ../src/openzwave-groups.cc:18:
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3416:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local                                                                    <v8::Value>, v8::Local<v8::Value>)’
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3416:37: note:   candidate expects 3 arguments, 2 provided
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3419:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t,                                                                     v8::Local<v8::Value>)’
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3419:37: note:   candidate expects 3 arguments, 2 provided
../src/openzwave-groups.cc:102:4: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<                                                                    v8::Integer>::return_t)’
    );
    ^
In file included from ../src/openzwave.hpp:27,
                 from ../src/openzwave-groups.cc:18:
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3416:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local                                                                    <v8::Value>, v8::Local<v8::Value>)’
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3416:37: note:   candidate expects 3 arguments, 2 provided
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3419:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t,                                                                     v8::Local<v8::Value>)’
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3419:37: note:   candidate expects 3 arguments, 2 provided
../src/openzwave-groups.cc:104:44: error: no matching function for call to ‘v8::Array::Set(Nan::imp::IntegerFactory<v8::Integer>::return_t,                                                                     v8::Local<v8::Object>&)’
    o_assocs->Set(Nan::New<Integer>(i), info);
                                            ^
In file included from ../src/openzwave.hpp:27,
                 from ../src/openzwave-groups.cc:18:
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3416:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local                                                                    <v8::Value>, v8::Local<v8::Value>)’
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3416:37: note:   candidate expects 3 arguments, 2 provided
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3419:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t,                                                                     v8::Local<v8::Value>)’
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h:3419:37: note:   candidate expects 3 arguments, 2 provided
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/13.0.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node:                                                                    :ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallback                                                                    Info<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/13.0.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<                                                                    P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const                                                                     v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
/home/sofian/Documents/node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/13.0.1/include/node/v8.h:10092:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::                                                                    ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackIn                                                                    fo<void>&)’} [-Wcast-function-type]
make: *** [openzwave_shared.target.mk:146: Release/obj.target/openzwave_shared/src/openzwave-groups.o] Error 1
make : on quitte le répertoire « /home/sofian/Documents/node_modules/openzwave-shared/build »
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.0-6-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sofian/Documents/node_modules/openzwave-shared
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/sofian/Documents/package.json'
npm WARN Documents No description
npm WARN Documents No repository field.
npm WARN Documents No README data
npm WARN Documents No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.5.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-02T10_58_21_837Z-debug.log
```

**Comment by matteodisabatino** [comment]
Do you use node 12?

**Comment by byte13** [comment]
Same error here with node 13.2.0 compiled from source on Raspbian : 
...
../src/openzwave-groups.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE OZW::OZW::GetAssociationsInstances(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/openzwave-groups.cc:98:4: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’    );
                                                                                                                                            ^
...
/root/.cache/node-gyp/13.2.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided ../src/openzwave-groups.cc:102:4: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’     );
                                                                                                                                             ^
...
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/openzwave-shared
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.5.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-25T18_37_03_996Z-debug.log

Many thank's inadvance for any help.

**Comment by carlbonsu** [comment]
I’m experiencing the same issue as reported by @byte13

**Comment by piec** [comment]
Same issue here.

This patch fixes the build. I'm absolutely not sure that it is correct at runtime though.

```diff
diff --git a/src/openzwave-groups.cc b/src/openzwave-groups.cc
index 1c179d1..bd21b7f 100644
--- a/src/openzwave-groups.cc
+++ b/src/openzwave-groups.cc
@@ -93,15 +93,17 @@ namespace OZW {
                for (uint8 i = 0; i < numNodes; i++) {
                        Local <Object> info = Nan::New<Object>();
                        info->Set(
+                               Isolate::GetCurrent()->GetCurrentContext(),
                                Nan::New<String>("instance").ToLocalChecked(),
                                Nan::New<Integer>(associations[i].m_instance)
                        );
                        info->Set(
+                               Isolate::GetCurrent()->GetCurrentContext(),
                                Nan::New<String>("nodeid").ToLocalChecked(),
                                Nan::New<Integer>(associations[i].m_nodeId)
                        );
 
-                       o_assocs->Set(Nan::New<Integer>(i), info);
+                       o_assocs->Set(Isolate::GetCurrent()->GetCurrentContext(), Nan::New<Integer>(i), info);
                }
 
                if (numNodes > 0) {
```

**Comment by byte13** [comment]
Many thank's Piec.
