### ISSUE TITLE
Error running "npm install openzwave-shared" on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by Rodarin** [OpenZWave/node-openzwave-shared#396]
```
npm ERR! code 1
npm ERR! path /home/android/Repos/Rodarin/podzwave/node_modules/openzwave-shared
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/android/.npm/_logs/2021-11-05T16_08_20_703Z-debug.log
```
Here are the contents of the debug log file:

```
0 verbose cli [
0 verbose cli   '/snap/node/5485/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   'openzwave-shared'
0 verbose cli ]
1 info using npm@8.1.3
2 info using node@v14.18.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/android/Repos/Rodarin/podzwave/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/android/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 16ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree:init Completed in 81ms
29 timing idealTree:userRequests Completed in 2ms
30 silly idealTree buildDeps
31 silly fetch manifest openzwave-shared@*
32 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
33 http fetch GET 200 https://registry.npmjs.org/openzwave-shared 109ms (cache hit)
34 silly placeDep ROOT openzwave-shared@1.7.2 OK for: podzwave@1.0.0 want: *
35 silly fetch manifest nan@>=2.14.0
36 http fetch GET 200 https://registry.npmjs.org/nan 5ms (cache hit)
37 timing idealTree:#root Completed in 123ms
38 silly placeDep ROOT nan@2.15.0 OK for: openzwave-shared@1.7.2 want: >=2.14.0
39 timing idealTree:node_modules/openzwave-shared Completed in 2ms
40 timing idealTree:node_modules/nan Completed in 0ms
41 timing idealTree:buildDeps Completed in 125ms
42 timing idealTree:fixDepFlags Completed in 1ms
43 timing idealTree Completed in 212ms
44 timing reify:loadTrees Completed in 214ms
45 timing reify:diffTrees Completed in 3ms
46 silly reify moves {}
47 timing reify:retireShallow Completed in 0ms
48 timing reify:createSparse Completed in 1ms
49 timing reify:loadBundles Completed in 0ms
50 silly audit bulk request {
50 silly audit   '@gar/promisify': [ '1.1.2' ],
50 silly audit   '@npmcli/fs': [ '1.0.0' ],
50 silly audit   '@npmcli/move-file': [ '1.1.2' ],
50 silly audit   '@tootallnate/once': [ '1.1.2' ],
50 silly audit   abbrev: [ '1.1.1' ],
50 silly audit   'agent-base': [ '6.0.2' ],
50 silly audit   agentkeepalive: [ '4.1.4' ],
50 silly audit   'aggregate-error': [ '3.1.0' ],
50 silly audit   'ansi-regex': [ '2.1.1' ],
50 silly audit   aproba: [ '1.2.0' ],
50 silly audit   'are-we-there-yet': [ '1.1.7' ],
50 silly audit   'balanced-match': [ '1.0.2' ],
50 silly audit   'brace-expansion': [ '1.1.11' ],
50 silly audit   cacache: [ '15.3.0' ],
50 silly audit   chownr: [ '2.0.0' ],
50 silly audit   'clean-stack': [ '2.2.0' ],
50 silly audit   'code-point-at': [ '1.1.0' ],
50 silly audit   'concat-map': [ '0.0.1' ],
50 silly audit   'console-control-strings': [ '1.1.0' ],
50 silly audit   'core-util-is': [ '1.0.3' ],
50 silly audit   debug: [ '4.3.2' ],
50 silly audit   delegates: [ '1.0.0' ],
50 silly audit   depd: [ '1.1.2' ],
50 silly audit   encoding: [ '0.1.13' ],
50 silly audit   'env-paths': [ '2.2.1' ],
50 silly audit   'err-code': [ '2.0.3' ],
50 silly audit   'fs-minipass': [ '2.1.0' ],
50 silly audit   'fs.realpath': [ '1.0.0' ],
50 silly audit   gauge: [ '2.7.4' ],
50 silly audit   glob: [ '7.2.0' ],
50 silly audit   'graceful-fs': [ '4.2.8' ],
50 silly audit   'has-unicode': [ '2.0.1' ],
50 silly audit   'http-cache-semantics': [ '4.1.0' ],
50 silly audit   'http-proxy-agent': [ '4.0.1' ],
50 silly audit   'https-proxy-agent': [ '5.0.0' ],
50 silly audit   'humanize-ms': [ '1.2.1' ],
50 silly audit   'iconv-lite': [ '0.6.3' ],
50 silly audit   imurmurhash: [ '0.1.4' ],
50 silly audit   'indent-string': [ '4.0.0' ],
50 silly audit   'infer-owner': [ '1.0.4' ],
50 silly audit   inflight: [ '1.0.6' ],
50 silly audit   inherits: [ '2.0.4' ],
50 silly audit   ip: [ '1.1.5' ],
50 silly audit   'is-fullwidth-code-point': [ '1.0.0' ],
50 silly audit   'is-lambda': [ '1.0.1' ],
50 silly audit   isarray: [ '1.0.0' ],
50 silly audit   isexe: [ '2.0.0' ],
50 silly audit   'lru-cache': [ '6.0.0' ],
50 silly audit   'make-fetch-happen': [ '9.1.0' ],
50 silly audit   minimatch: [ '3.0.4' ],
50 silly audit   minipass: [ '3.1.5' ],
50 silly audit   'minipass-collect': [ '1.0.2' ],
50 silly audit   'minipass-fetch': [ '1.4.1' ],
50 silly audit   'minipass-flush': [ '1.0.5' ],
50 silly audit   'minipass-pipeline': [ '1.2.4' ],
50 silly audit   'minipass-sized': [ '1.0.3' ],
50 silly audit   minizlib: [ '2.1.2' ],
50 silly audit   mkdirp: [ '1.0.4' ],
50 silly audit   ms: [ '2.1.2' ],
50 silly audit   negotiator: [ '0.6.2' ],
50 silly audit   'node-gyp': [ '8.4.0' ],
50 silly audit   nopt: [ '5.0.0' ],
50 silly audit   npmlog: [ '4.1.2' ],
50 silly audit   'number-is-nan': [ '1.0.1' ],
50 silly audit   'object-assign': [ '4.1.1' ],
50 silly audit   once: [ '1.4.0' ],
50 silly audit   'p-map': [ '4.0.0' ],
50 silly audit   'path-is-absolute': [ '1.0.1' ],
50 silly audit   'process-nextick-args': [ '2.0.1' ],
50 silly audit   'promise-inflight': [ '1.0.1' ],
50 silly audit   'promise-retry': [ '2.0.1' ],
50 silly audit   'readable-stream': [ '2.3.7' ],
50 silly audit   retry: [ '0.12.0' ],
50 silly audit   rimraf: [ '3.0.2' ],
50 silly audit   'safe-buffer': [ '5.1.2' ],
50 silly audit   'safer-buffer': [ '2.1.2' ],
50 silly audit   semver: [ '7.3.5' ],
50 silly audit   'set-blocking': [ '2.0.0' ],
50 silly audit   'signal-exit': [ '3.0.5' ],
50 silly audit   'smart-buffer': [ '4.2.0' ],
50 silly audit   socks: [ '2.6.1' ],
50 silly audit   'socks-proxy-agent': [ '6.1.0' ],
50 silly audit   ssri: [ '8.0.1' ],
50 silly audit   string_decoder: [ '1.1.1' ],
50 silly audit   'string-width': [ '1.0.2' ],
50 silly audit   'strip-ansi': [ '3.0.1' ],
50 silly audit   tar: [ '6.1.11' ],
50 silly audit   'unique-filename': [ '1.1.1' ],
50 silly audit   'unique-slug': [ '2.0.2' ],
50 silly audit   'util-deprecate': [ '1.0.2' ],
50 silly audit   which: [ '2.0.2' ],
50 silly audit   'wide-align': [ '1.1.5' ],
50 silly audit   wrappy: [ '1.0.2' ],
50 silly audit   yallist: [ '4.0.0' ],
50 silly audit   'openzwave-shared': [ '1.7.2' ],
50 silly audit   nan: [ '2.15.0' ]
50 silly audit }
51 timing reifyNode:node_modules/openzwave-shared Completed in 73ms
52 timing reifyNode:node_modules/nan Completed in 73ms
53 timing reify:unpack Completed in 74ms
54 timing reify:unretire Completed in 0ms
55 timing build:queue Completed in 1ms
56 info run openzwave-shared@1.7.2 preinstall node_modules/openzwave-shared node lib/install-ozw.js
57 info run openzwave-shared@1.7.2 preinstall { code: 0, signal: null }
58 timing build:run:preinstall:node_modules/openzwave-shared Completed in 83ms
59 timing build:run:preinstall Completed in 83ms
60 info run openzwave-shared@1.7.2 install node_modules/openzwave-shared node-gyp rebuild
61 info run openzwave-shared@1.7.2 install { code: 1, signal: null }
62 timing reify:rollback:createSparse Completed in 23ms
63 timing reify:rollback:retireShallow Completed in 0ms
64 timing command:install Completed in 532ms
65 verbose stack Error: command failed
65 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
65 verbose stack     at ChildProcess.emit (events.js:400:28)
65 verbose stack     at maybeClose (internal/child_process.js:1058:16)
65 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
66 verbose pkgid openzwave-shared@1.7.2
67 verbose cwd /home/android/Repos/Rodarin/podzwave
68 verbose Linux 5.4.0-89-generic
69 verbose argv "/snap/node/5485/bin/node" "/usr/local/bin/npm" "install" "openzwave-shared"
70 verbose node v14.18.1
71 verbose npm  v8.1.3
72 error code 1
73 error path /home/android/Repos/Rodarin/podzwave/node_modules/openzwave-shared
74 error command failed
75 error command sh -c node-gyp rebuild
76 verbose exit 1
```
Admittedly I am very new to node and openzwave, but I was unable to find a solution on my own. I cloned and built the latest OpenZWave and followed the readme directions, including the commands in Notice 1 and Notice 2.

**Comment by robertsLando** [comment]
Switch to zwave-js. OZW is died

**Comment by Rodarin** [comment]
zwave-js does not support Android/termux. If this project is dead, please unpin it and mark it as dead.

**Comment by robertsLando** [comment]
> zwave-js does not support Android/termux

What do you mean with this? If you are using openzwave shared you could easily replace it with zwave-js 😕
