### ISSUE TITLE
Cannot install on Debian Jessie/Raspberry Pi 2.

### ISSUE THREAD

**Issue by Stubbs** [OpenZWave/node-openzwave-shared#53]
I get the following when trying to install on a RaspberryPi 2 running Debian Jessie. I get the same if I install the openzwave node module too, when it tries to install the shared dependancy.

I have the openzwave library installed, I just built that from source itself.

```
pi@raspberrypi-c:~/.node-red $ npm install openzwave-shared
\
> openzwave-shared@1.1.6 preinstall /home/pi/.node-red/node_modules/openzwave-shared
> node lib/install-ozw.js

|
> openzwave-shared@1.1.6 install /home/pi/.node-red/node_modules/openzwave-shared
> node-gyp rebuild

make: Entering directory '/home/pi/.node-red/node_modules/openzwave-shared/build'
  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
In file included from ../src/openzwave.hpp:27:0,
                 from ../src/callbacks.cc:18:
/home/pi/.node-red/node_modules/openzwave-shared/node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
openzwave_shared.target.mk:105: recipe for target 'Release/obj.target/openzwave_shared/src/callbacks.o' failed
make: *** [Release/obj.target/openzwave_shared/src/callbacks.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/openzwave-shared/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/openzwave-shared
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! openzwave-shared@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.1.6 install script.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "openzwave-shared"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ekarak** [comment]
This looks to be an error with the latest NAN.
You also seem to have very old node and gyp:
gyp ERR! cwd /home/pi/.node-red/node_modules/openzwave-shared
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
Could you please try upgrading your node.js to 0.12? see http://node-arm.herokuapp.com/

**Comment by ekarak** [comment]
Is this still an issue?

**Comment by Stubbs** [comment]
No, using a later version of Node fixed it, though I only managed to confirm it last night.
