### ISSUE TITLE
cannot find -lopenzwave - npm install

### ISSUE THREAD

**Issue by polarathene** [OpenZWave/node-openzwave-shared#68]
Arch Linux x64 Kernel 4.3.3, Node 5.5.0, NPM 3.7.1
I've downloaded both v1.4 and master of OpenZWave, ran `make && sudo make install` as instructed. All seems well, I go into my project folder and run `npm install openzwave-shared`, then get the error `cannot find -lopenzwave`.

Not quite sure what I've done wrong?

Following full output:
```
$ npm install openzwave-shared

> openzwave-shared@1.1.7 preinstall /home/polarathene/projects/zwave_test/node_modules/.staging/openzwave-shared-4963d866
> node lib/install-ozw.js


> openzwave-shared@1.1.7 install /home/polarathene/projects/zwave_test/node_modules/openzwave-shared
> node-gyp rebuild

make: Entering directory '/home/polarathene/projects/zwave_test/node_modules/openzwave-shared/build'
  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-config.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-driver.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-groups.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-management.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-network.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-nodes.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-polling.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-scenes.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-values.o
  CXX(target) Release/obj.target/openzwave_shared/src/utils.o
  SOLINK_MODULE(target) Release/obj.target/openzwave_shared.node
/usr/bin/ld: cannot find -lopenzwave
collect2: error: ld returned 1 exit status
openzwave_shared.target.mk:142: recipe for target 'Release/obj.target/openzwave_shared.node' failed
make: *** [Release/obj.target/openzwave_shared.node] Error 1
make: Leaving directory '/home/polarathene/projects/zwave_test/node_modules/openzwave-shared/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.3-3-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/polarathene/projects/zwave_test/node_modules/openzwave-shared
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN zwave_test@1.0.0 No description
npm WARN zwave_test@1.0.0 No repository field.
npm ERR! Linux 4.3.3-3-ARCH
npm ERR! argv "/usr/bin/node" "/usr/sbin/npm" "install" "openzwave-shared"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.1.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by polarathene** [comment]
The build placed `libopenzwave.so` and `libopenzwave.so.1.4` into `/usr/local/lib64`. I used terminal command `ld -lopenzwave --verbose` to get a list of paths it looks for, `/usr/local/lib` is one of them. I had no luck finding a way to add lib64 path, so have gone with a symlink.

`sudo ln -s /usr/local/lib64/libopenzwave.so /usr/local/lib/libopenzwave.so` creates symlink so that the file appears to be in the location that `ld` looks in. Running NPM Install afterwards was successful :)

**Comment by ekarak** [comment]
Thanks for the feedback!
You're right, I think I've raised this library path issue in the main OpenZWave project a while ago. Going to check what happened with this. 
BTW, if you got time, do you think you can commit a pull request to add this note to the readme's ?
