### ISSUE TITLE
TypeError: setValue: OpenZWave valueId not found

### ISSUE THREAD

**Issue by polarathene** [OpenZWave/node-openzwave-shared#70]
So I've taken the [example code](https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-example.md) and changed what happens after scan complete. I'm using Antergos(Arch Linux) x64 with Node 5.5 and NPM 3.7 if that helps at all. Running v1.1.7 of the package, have also installed git version with no difference.

The ZWave controller is an Aeotec Gen5 USB stick which I paired to an Aeotec light bulb. It's device path had to be changed from the suggested ttyUSB0 to ttyACM0(shouldn't be a problem?).

Trying to just get the dim feature to work with the following commands:
`zwave.setValue( {nodeid:2, class_id: 38, instance:1, index:0}, 50);`
`zwave.setValue( 2, 38, 1, 0, 50);`

produces the error:
```
TypeError: setValue: OpenZWave valueId not found
    at TypeError (native)
    at EventEmitter.<anonymous> (/home/polarathene/projects/zwave_test/index.js:122:7)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at addonModule.Emitter.emit (/home/polarathene/projects/zwave_test/node_modules/openzwave-shared/lib/openzwave-shared.js:39:5)
```

`zwave.setLevel(2, 50);`

produces the error:
```
TypeError: zwave.setLevel is not a function
    at EventEmitter.<anonymous> (/home/polarathene/projects/zwave_test/index.js:123:7)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at addonModule.Emitter.emit (/home/polarathene/projects/zwave_test/node_modules/openzwave-shared/lib/openzwave-shared.js:39:5)
```

Log prior to running code after scan completes:
```
2016-02-11 15:11:00.870 Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
2016-02-11 15:11:00.870 Warning, CheckCompletedNodeQueries all=1, deadFound=0 sleepingOnly=1
2016-02-11 15:11:00.870 Info,          Node query processing complete.
2016-02-11 15:11:00.870 Detail, Node002, Notification: NodeQueriesComplete
2016-02-11 15:11:00.870 Detail, contrlr, Notification: AllNodesQueried
node2: Aeotec, LED Bulb
node2: name="", type="Light Dimmer Switch", location=""
node2: class 38
node2:   Level=99
node2:   Bright=undefined
node2:   Dim=undefined
node2:   Ignore Start Level=true
node2:   Start Level=0
node2: class 39
node2:   Switch All=On and Off Enabled
node2: class 51
node2:   Color=#FF00003300
node2:   Color Index=Red
node2:   Color Channels=31
node2: class 94
node2:   ZWave+ Version=1
node2:   InstallerIcon=1536
node2:   UserIcon=1536
node2: class 112
node2:   Send out a report when the color is changed=Disable
node2:   Use External Switch to turn on/off the bulb=Disable
node2:   Use External Switch to changes the bulb color=Enable
node2:   Colorful mode=Un-reboot Colorful mode
node2:   Colorful mode configuration=3840
node2:   Color index configuration when the bulb is in Multi color mode=-2023406815
node2:   Send notifications to associated devices (Lifeline)=Basic
node2:   Partner ID=Aeon Labs Standard Product
node2:   Lock/Unlock Configuration=Unlock
node2:   Reset default configuration=0
node2: class 115
node2:   Powerlevel=-7dB
node2:   Timeout=0
node2:   Set Powerlevel=undefined
node2:   Test Node=0
node2:   Test Powerlevel=Normal
node2:   Frame Count=0
node2:   Test=undefined
node2:   Report=undefined
node2:   Test Status=Failed
node2:   Acked Frames=0
node2: class 134
node2:   Library Version=3
node2:   Protocol Version=4.05
node2:   Application Version=1.04
====> scan complete, hit ^C to finish.
```

The device is clearly paired from what I can tell with the log, and it's node is 2? Oddly I remember trying the colour command class(51) first and getting similar errors, the light has not changed colour but the report aboves says the value is `#FF00003300` which is what I set from `#000000FF00`. Class 38's value hasn't updated though. 

I am new to ZWave, as well as this library, so I'm not sure if I entered the colour value right, since I can't seem to turn it on/off(no class 37?) and I'm getting errors with dimming(class 38) I am pretty sure this is a bug?

**Comment by polarathene** [comment]
I just tried the colour class 51 again, but this time removed the warm white value so it was only red assigned `#FF00000000`, it's turned red with no error :) Still confused with what I've done wrong with the class 38.

EDIT: I made a typo with the setValue without an object, I was still targeting class 37. The attempt with correct class with an object value was wrong because `nodeid` should be `node_id`, documentation example needs to be updated, will see if I can put together a PR for you :)
