### ISSUE TITLE
Mac OS X Install Error

### ISSUE THREAD

**Issue by rgstephens** [OpenZWave/node-openzwave-shared#84]
I'm running into the following error at install:

```
npm install node-red-contrib-openzwave
 
> openzwave-shared@1.1.9 preinstall /Users/greg/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared
> node lib/install-ozw.js


> typechecker@2.0.8 preinstall /Users/greg/.node-red/node_modules/node-red-contrib-openzwave/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> openzwave-shared@1.1.9 install /Users/greg/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config --variable=libdir libopenzwave' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/greg/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-red-contrib-openzwave"
npm ERR! node v0.12.2
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.1.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/greg/.node-red/npm-debug.log
```

**Comment by ekarak** [comment]
Looks like the `pkg-config --variable=libdir libopenzwave` command that's being run by node-gyp failed. This is a helper tool that prints out OpenZWave's installation parameters. What's the output of  `which pkgconfig` ?

**Comment by rgstephens** [comment]
Thanks, pkg-config was not installed.  I installed it and now receive:

```
> openzwave-shared@1.1.9 preinstall /Users/greg/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared
> node lib/install-ozw.js

 
> openzwave-shared@1.1.9 install /Users/greg/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared
> node-gyp rebuild

Package libopenzwave was not found in the pkg-config search path.
Perhaps you should add the directory containing `libopenzwave.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libopenzwave' found
gyp: Call to 'pkg-config --variable=libdir libopenzwave' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/greg/.node-red/node_modules/node-red-contrib-openzwave/node_modules/openzwave-shared
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

> typechecker@2.0.8 preinstall /Users/greg/.node-red/node_modules/node-red-contrib-openzwave/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-red-contrib-openzwave"
npm ERR! node v0.12.2
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.1.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/greg/.node-red/npm-debug.log

```

**Comment by ekarak** [comment]
It seems you're missing OpenZWave . Have you installed it on your system?

**Comment by ekarak** [comment]
please take a look [at this comment](https://github.com/OpenZWave/node-openzwave-shared/issues/19#issuecomment-157118703) which describes how another MacOS user installed OpenZWave on his machine.

**Comment by ekarak** [comment]
I've updated the README file with some added comments on MacOS/X installation. Please do take a look and report any inconstencies you might find. (I have no access to a Mac)
