### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by goliatone** [OpenZWave/node-openzwave-shared#9]
`npm i openzwave-shared` fails with the following output:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/goliatone/NODEJS/node_modules/openzwave-shared
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! openzwave-shared@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.0.1 install script.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/usr/local/bin/npm" "i" "openzwave-shared"
npm ERR! cwd /Users/goliatone/NODEJS/zwave-shared-test
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/goliatone/NODEJS/zwave-shared-test/npm-debug.log
npm ERR! not ok code 0
```

Mac OS X 10.10.4

**Comment by ekarak** [comment]
Sorry, MacOS NOT supported. Please feel free to contribute!
Στις 8 Αυγ 2015 9:48 μ.μ., ο χρήστης "goliatone" <notifications@github.com>
έγραψε:

**Comment by goliatone** [comment]
ok, I see. Would this be able to run this on a raspberry pi?

**Comment by ekarak** [comment]
I have it already running on Raspbian :)
Στις 8 Αυγ 2015 11:24 μ.μ., ο χρήστης "goliatone" <notifications@github.com>
έγραψε:

**Comment by ekarak** [comment]
Closing issue. As stated on README, Mac is not supported.
